### ISSUE TITLE
Node details

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#13]
1) We should change the background color of this dialog (from black) to the same color as menu background. 
2) We should also increase font size a bit so that text is more readable.
3) When a node is selected, we should not pop-up the details dialog for any containing / parent nodes.

**Comment by istemi-bahceci** [comment]
Fixed 1,2 but third is about qtip library that i am using, trying to find a solution.

**Comment by ugurdogrusoz** [comment]
3rd is very critical though.

**Comment by ugurdogrusoz** [comment]
Also I don't see any change in font size (not any bigger)

**Comment by istemi-bahceci** [comment]
Fixed font size, submitted an issue about the qTip bug: https://github.com/cytoscape/cytoscape.js-qtip/issues/16

**Comment by istemi-bahceci** [comment]
fixed/

**Comment by ugurdogrusoz** [comment]
Great! As a minor improvement, can we put a scrollbar (or ... for expanding and collapsing the full text) for the text of Gene Summary? This is usually very long and takes up too much space, making it difficult to see the rest of the properties.

**Comment by ugurdogrusoz** [comment]
Interesting, this original problem of popping up the dialog for multiple nodes in nested case is not completely resolved. It still happens every now and then!

**Comment by ugurdogrusoz** [comment]
The duplication problem is gone but I don't see the inspector at all for top most (outer most) compounds when we have multiple levels of nesting. If A is inside B, which is inside C. Then clicking on C won't pop-up its inspector.

**Comment by ugurdogrusoz** [comment]
This looks fixed (I assume you didn't reopen it because there is a problem and am closing it).
